/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author pedro
 */
public class AreaMunicipio extends javax.swing.JFrame {

    /**
     * Creates new form AreaMunicipio
     */
    public AreaMunicipio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mParquesContentores = new javax.swing.JMenu();
        miCriarParque = new javax.swing.JMenuItem();
        miListarParque = new javax.swing.JMenuItem();
        mTrabalhadores = new javax.swing.JMenu();
        miCriarTrabalhador = new javax.swing.JMenuItem();
        miRemoverTrabalhador = new javax.swing.JMenuItem();
        miListarTrabalhadores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área do Município");
        setMinimumSize(new java.awt.Dimension(500, 525));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 340, 90, 30);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(379, 380, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Municipio.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 460);

        mParquesContentores.setText("Parques De Contentores");

        miCriarParque.setText("Criar Parque");
        miCriarParque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCriarParqueActionPerformed(evt);
            }
        });
        mParquesContentores.add(miCriarParque);

        miListarParque.setText("Listar Parques");
        miListarParque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarParqueActionPerformed(evt);
            }
        });
        mParquesContentores.add(miListarParque);

        jMenuBar1.add(mParquesContentores);

        mTrabalhadores.setText("Trabalhadores");

        miCriarTrabalhador.setText("Criar Trabalhador");
        miCriarTrabalhador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCriarTrabalhadorActionPerformed(evt);
            }
        });
        mTrabalhadores.add(miCriarTrabalhador);

        miRemoverTrabalhador.setText("Remover Trabalhador");
        miRemoverTrabalhador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemoverTrabalhadorActionPerformed(evt);
            }
        });
        mTrabalhadores.add(miRemoverTrabalhador);

        miListarTrabalhadores.setText("Listar Trabalhadores");
        miListarTrabalhadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarTrabalhadoresActionPerformed(evt);
            }
        });
        mTrabalhadores.add(miListarTrabalhadores);

        jMenuBar1.add(mTrabalhadores);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCriarParqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCriarParqueActionPerformed
        // TODO add your handling code here:
        
        CriarParquesContentores parque = new CriarParquesContentores();
        parque.setVisible(true);
        dispose();
    }//GEN-LAST:event_miCriarParqueActionPerformed

    private void miCriarTrabalhadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCriarTrabalhadorActionPerformed
        CriarTrabalhador tr = new CriarTrabalhador();
        tr.setVisible(true);
        dispose();
    }//GEN-LAST:event_miCriarTrabalhadorActionPerformed

    private void miRemoverTrabalhadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemoverTrabalhadorActionPerformed
        RemoverTrabalhador rt = new RemoverTrabalhador();
        rt.setVisible(true);
        dispose();
    }//GEN-LAST:event_miRemoverTrabalhadorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new LoginUtilizador().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void miListarParqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarParqueActionPerformed
        // TODO add your handling code here:
        ListarParquesMun p = new ListarParquesMun();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_miListarParqueActionPerformed

    private void miListarTrabalhadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarTrabalhadoresActionPerformed
        // TODO add your handling code here:
        ListarTrabalhadores lt = new ListarTrabalhadores();
        lt.setVisible(true);
        dispose();
 
    }//GEN-LAST:event_miListarTrabalhadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaMunicipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaMunicipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaMunicipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaMunicipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaMunicipio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mParquesContentores;
    private javax.swing.JMenu mTrabalhadores;
    private javax.swing.JMenuItem miCriarParque;
    private javax.swing.JMenuItem miCriarTrabalhador;
    private javax.swing.JMenuItem miListarParque;
    private javax.swing.JMenuItem miListarTrabalhadores;
    private javax.swing.JMenuItem miRemoverTrabalhador;
    // End of variables declaration//GEN-END:variables
}
