/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author pedro
 */
public class AreaEquipa extends javax.swing.JFrame {

    /**
     * Creates new form AreaEquipa
     */
    public AreaEquipa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSair = new javax.swing.JButton();
        bVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mOrdensServico = new javax.swing.JMenu();
        miListarOrdens = new javax.swing.JMenuItem();
        miPesquisarOrdens = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miPesquisarParque = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área de Equipa");
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });
        getContentPane().add(bSair);
        bSair.setBounds(350, 230, 80, 30);

        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(bVoltar);
        bVoltar.setBounds(350, 270, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Main.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-110, 0, 620, 370);

        mOrdensServico.setText("Ordens de Serviço");

        miListarOrdens.setText("Listar Ordens ");
        miListarOrdens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarOrdensActionPerformed(evt);
            }
        });
        mOrdensServico.add(miListarOrdens);

        miPesquisarOrdens.setText("Pesquisar");
        miPesquisarOrdens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPesquisarOrdensActionPerformed(evt);
            }
        });
        mOrdensServico.add(miPesquisarOrdens);

        jMenuBar1.add(mOrdensServico);

        jMenu2.setText("Parques de Contentores");

        miPesquisarParque.setText("Pesquisar");
        jMenu2.add(miPesquisarParque);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bSairActionPerformed

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        // TODO add your handling code here:
        new LoginUtilizador().setVisible(true);
        dispose();
    }//GEN-LAST:event_bVoltarActionPerformed

    private void miListarOrdensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarOrdensActionPerformed
        // TODO add your handling code here:
        ListarOrdem lo = new ListarOrdem();
        lo.setVisible(true);
        dispose();
    }//GEN-LAST:event_miListarOrdensActionPerformed

    private void miPesquisarOrdensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPesquisarOrdensActionPerformed
        // TODO add your handling code here:
        ProcurarOrdemEq p = new ProcurarOrdemEq();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_miPesquisarOrdensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaEquipa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaEquipa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaEquipa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaEquipa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaEquipa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSair;
    private javax.swing.JButton bVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mOrdensServico;
    private javax.swing.JMenuItem miListarOrdens;
    private javax.swing.JMenuItem miPesquisarOrdens;
    private javax.swing.JMenuItem miPesquisarParque;
    // End of variables declaration//GEN-END:variables
}
