/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.Repository;
import BLL.Trabalhadores;
import BLL.Utilizador;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class CriarTrabalhador extends javax.swing.JFrame {

    /**
     * Creates new form CriarTrabalhador
     */
    public CriarTrabalhador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtNif = new javax.swing.JTextField();
        txtnSegSocial = new javax.swing.JTextField();
        txtContacto = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        bCriar = new javax.swing.JButton();
        bVoltar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criar Trabalhador");
        setPreferredSize(new java.awt.Dimension(500, 525));
        getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(46, 38, 80, 20);

        jLabel2.setText("NIF:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(46, 101, 60, 20);

        jLabel4.setText("Nº Segurança Social:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(46, 164, 180, 20);

        jLabel5.setText("Contacto:");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(46, 227, 100, 20);

        jLabel6.setText("Salário:");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 290, 80, 20);
        getContentPane().add(txtNome);
        txtNome.setBounds(46, 61, 333, 30);

        txtNif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNifActionPerformed(evt);
            }
        });
        getContentPane().add(txtNif);
        txtNif.setBounds(46, 124, 333, 30);
        getContentPane().add(txtnSegSocial);
        txtnSegSocial.setBounds(50, 190, 333, 30);
        getContentPane().add(txtContacto);
        txtContacto.setBounds(50, 250, 333, 30);
        getContentPane().add(txtSalario);
        txtSalario.setBounds(50, 320, 333, 30);

        bCriar.setText("Criar");
        bCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCriarActionPerformed(evt);
            }
        });
        getContentPane().add(bCriar);
        bCriar.setBounds(330, 390, 100, 30);

        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(bVoltar);
        bVoltar.setBounds(200, 390, 100, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Municipio.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 0, 550, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNifActionPerformed

    private void bCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCriarActionPerformed
        // TODO add your handling code here:
        Trabalhadores trabalhadores = new Trabalhadores();
        
        String nome = txtNome.getText();
        int nifTrabalhador = Integer.parseInt(this.txtNif.getText());
        int nSegSocial = Integer.parseInt(this.txtnSegSocial.getText());
        int contacto = Integer.parseInt(this.txtContacto.getText());
        int salario = Integer.parseInt(this.txtSalario.getText());
        
        boolean suc = false;
        
        trabalhadores.setNome(nome);
        trabalhadores.setNifTrabalhador(nifTrabalhador);
        trabalhadores.setnSegSocial(nSegSocial);
        trabalhadores.setContacto(contacto);
        trabalhadores.setSalario(salario);
        suc = true;
        
        if (suc == true) {
                    Iterator<Trabalhadores> iter = Repository.getInstance().getTrabalhadores().iterator();
                    while (iter.hasNext()) {
                        Trabalhadores t = iter.next();

                    }
                    Repository.getInstance().novoTrabalhador(trabalhadores);
                JOptionPane.showMessageDialog(this.bCriar, "Trabalhador adicionado com sucesso!");
                }else{
                    JOptionPane.showMessageDialog(this.bCriar, "Informação inserida incorretamente!");
                }
                dispose();
       
        
    }//GEN-LAST:event_bCriarActionPerformed

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        // TODO add your handling code here:

        new AreaMunicipio().setVisible(true);
        dispose();
    }//GEN-LAST:event_bVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarTrabalhador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCriar;
    private javax.swing.JButton bVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtNif;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtnSegSocial;
    // End of variables declaration//GEN-END:variables
}
