/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BLL.Repository;
import BLL.Trabalhadores;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class RemoverTrabalhador extends javax.swing.JFrame {

    private Iterator<Integer> trabalhadores;

    /**
     * Creates new form RemoverTrabalhador
     */
    public RemoverTrabalhador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNif = new javax.swing.JTextField();
        bVoltar = new javax.swing.JButton();
        bRemover = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remover Trabalhador");
        setPreferredSize(new java.awt.Dimension(500, 525));
        getContentPane().setLayout(null);

        jLabel2.setText("NIF:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 154, 70, 20);
        getContentPane().add(txtNif);
        txtNif.setBounds(50, 180, 377, 30);

        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(bVoltar);
        bVoltar.setBounds(170, 380, 100, 30);

        bRemover.setText("Remover");
        bRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(bRemover);
        bRemover.setBounds(320, 380, 89, 33);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Municipio.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, -10, 570, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverActionPerformed
        // TODO add your handling code here:
        Trabalhadores trabalhadores = new Trabalhadores();
        
        for(int i = 0; i < trabalhadores.size(); i++){
            Trabalhadores tb = trabalhadores.get(i);
        
        
            if(tb.getNome().equals(txtNif.getText())){
                trabalhadores.remove(tb);
                break;
            }    
        }
        Repository.serializar("Repositorio.dat");
        JOptionPane.showMessageDialog(null, "Removido com sucesso!");
        
        new AreaMunicipio().setVisible(true);
        dispose();
    }//GEN-LAST:event_bRemoverActionPerformed

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        // TODO add your handling code here:

        new AreaMunicipio().setVisible(true);
        dispose();
    }//GEN-LAST:event_bVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverTrabalhador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRemover;
    private javax.swing.JButton bVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtNif;
    // End of variables declaration//GEN-END:variables
}
